[source]
center = [0.5, 0.5, 0.0]
radius = 0.10
amplitude = 0.1
frequency = 10

[material]
inclusion_density = 2.0
inclusion_wave_speed = 2.0
outer_density = 1.0
outer_wave_speed = 1.0

[mesh]
grid_size = 0.03
box_size = 1.00
inclusion_center = [0.5, 0.5, 0.5]
inclusion_scaling = [0.22, 0.18, 0.18]
inclusion_rotation = [0.12, 0.08, 0.08]

[solver]
number_of_timesteps = 4000
polynomial_order = 2

[receivers]
#top_sensors = 15
#side_sensors = 10
sensors_per_face = 9

[output_intervals]
image = 4000
data = 4000
points = 10
energy = 0
