[source]
center = [0.125, 0.125, 0.0]
radius = 0.02
amplitude = 0.1
frequency = 40

[material]
inclusion_density = 1.5
inclusion_wave_speed = 0.5
outer_density = 1.0
outer_wave_speed = 1.0

[mesh]
grid_size = 0.01
box_size = 0.25
inclusion_radius = 0.05

[solver]
number_of_timesteps = 26
polynomial_order = 2

[receivers]
top_sensors = 15
side_sensors = 10

[output_intervals]
image = 0
data = 0
points = 10
energy = 0
