[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wave_map"
version = "0.1.0"
description = "Wave Map"
readme = "README.md"
license = "MIT"
authors = [
    {name = "luke"}
]
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20.0",
    "scipy>=1.7.0", 
    "matplotlib>=3.5.0",
    "gmsh>=4.8.0",
    "pyvista>=0.35.0",
    "panel>=1.0.0",
    "sympy>=1.9.0",
    "tomli>=2.0.0",
    "toml>=0.10.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0.0",
    "black>=22.0.0",
]
[tool.setuptools]
package-dir = {"" = "src"}  # Add this section to point to your src directory

[project.scripts]
wave_map = "wave_map.cli.run_simulation:main"
run_simulation = "wave_map.cli.run_simulation:main"
run_simulation_batch = "wave_map.cli.run_simulation_batch:main"
run_gui = "wave_map.cli.run_gui:main"
train_and_test_ppe = "wave_map.cli.train_and_test_ppe:main"

#[tool.setuptools.package-data]
## Include default TOML configs inside wave_simulator package
#"simulator" = ["config/*.toml"]

[tool.setuptools.package-data]
wave_map.config = ["*.toml"]

[tool.setuptools.packages.find]
where = ["src"]
